services:
  # Serviço 1: O Bot WhatsApp (Aplicação Web)
  - type: web
    name: bot-whatsapp
    env: node
    region: oregon # Região onde o serviço será hospedado
    plan: free # Plano gratuito para o serviço web
    buildFilter:
      paths:
        - src/**
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: DATABASE_URL # Nome da variável de ambiente
        fromService:
          type: pserv
          name: postgres-whatsapp
          property: connectionString
      - key: PORT
        value: 10000
      - key: NODE_VERSION
        value: 18.18.2

  # Serviço 2: Banco de Dados PostgreSQL
  - type: pserv
    name: postgres-whatsapp
    env: postgres
    region: oregon # É bom manter a mesma região do bot para baixa latência
    plan: free # Plano gratuito para o banco de dados
    postgresMajorVersion: 13
    disk:
      name: postgres-data
      sizeGB: 1
      mountPath: /var/lib/postgresql/data
