# Arquivo de configuração para a plataforma Render.com

services:
  # Serviço da Aplicação Web (o seu bot ou API)
  - type: web
    name: minha-automacao
    env: python
    buildCommand: "./build.sh"
    startCommand: "python app.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: postgres
          property: connectionString # <-- Agora isso vai funcionar, pois o serviço 'postgres' estará válido.
      - key: TELEGRAM_BOT_TOKEN
        sync: false

  # Serviço do Banco de Dados PostgreSQL Gerenciado
  - type: pserv
    name: postgres
    # <-- CORREÇÃO PRINCIPAL: A linha "env: postgres" foi removida.
    # A Render já sabe o que fazer com um "type: pserv". Não são necessárias mais instruções de runtime.
    disk:
      name: postgres-data
      mountPath: /var/lib/postgresql/data
      sizeGB: 1
