services:
  # Serviço 1: A instância do n8n
  - type: web
    name: n8n-agencia
    env: node
    plan: free # Você pode ajustar para um plano pago se precisar de mais performance
    region: oregon # Escolha a região mais próxima de você ou de seus clientes
    buildCommand: npm install
    startCommand: npx n8n start
    healthCheckPath: /healthz
    envVars:
      - key: N8N_HOST
        value: n8n-agencia.onrender.com
      - key: N8N_PORT
        value: 10000
      - key: N8N_PROTOCOL
        value: https
      - key: NODE_ENV
        value: production
      - key: WEBHOOK_URL
        value: https://n8n-agencia.onrender.com
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        fromService:
          type: pserv
          name: n8n-db
          property: host
      - key: DB_POSTGRESDB_PORT
        fromService:
          type: pserv
          name: n8n-db
          property: port
      - key: DB_POSTGRESDB_DATABASE
        fromService:
          type: pserv
          name: n8n-db
          property: database
      - key: DB_POSTGRESDB_USER
        fromService:
          type: pserv
          name: n8n-db
          property: user
      - key: DB_POSTGRESDB_PASSWORD
        fromService:
          type: pserv
          name: n8n-db
          property: password
    # CORREÇÃO 1: O bloco 'disks' agora está corretamente indentado DENTRO do serviço 'n8n-agencia'.
    disks:
      - name: n8n-data
        mountPath: /home/node/.n8n
        sizeGB: 1

  # Serviço 2: O banco de dados PostgreSQL
  - type: pserv
    name: n8n-db
    plan: free
    region: oregon
    # CORREÇÃO 2 e 3: 'repository' e 'tag' foram combinados na propriedade 'image'.
    image: postgres:13
    disk:
      name: n8n-postgres-data
      mountPath: /var/lib/postgresql/data
      sizeGB: 1
