# Arquivo de configuração para a plataforma Render.com
# Define os serviços da aplicação (servidor web e banco de dados).

services:
  # Serviço 1: Aplicação principal (o bot/servidor web)
  - type: web
    name: automacao-whatsapp
    env: node
    plan: free # Plano gratuito, ideal para testes e desenvolvimento. Mude se precisar de mais recursos.
    buildCommand: 'npm install'
    startCommand: 'node app.js'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres-whatsapp
          property: connectionString
      - key: NODE_VERSION
        value: 18.17.1 # Especifica a versão do Node.js

  # Serviço 2: Banco de Dados PostgreSQL
  - type: pserv
    name: postgres-whatsapp
    env: postgres # Ambiente PostgreSQL
    plan: free # Plano gratuito para o banco de dados.
    postgresMajorVersion: 13
    disk:
      name: postgres-data
      sizeGB: 1 # 1 GB de armazenamento para o banco de dados.
