services:
  # Serviço para o n8n
  - name: n8n
    type: web
    env: docker
    repo: https://github.com/n8n-io/n8n.git # Repositório oficial do n8n como exemplo
    branch: master
    dockerfilePath: ./packages/cli/docker/images/n8n-debian/Dockerfile
    envVars:
      - key: N8N_HOST
        fromService:
          type: web
          name: n8n
          property: url
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        fromService:
          type: pserv
          name: postgres
          property: host
      - key: DB_POSTGRESDB_PORT
        fromService:
          type: pserv
          name: postgres
          property: port
      - key: DB_POSTGRESDB_DATABASE
        fromService:
          type: pserv
          name: postgres
          property: database
      - key: DB_POSTGRESDB_USER
        fromService:
          type: pserv
          name: postgres
          property: user
      - key: DB_POSTGRESDB_PASSWORD
        fromService:
          type: pserv
          name: postgres
          property: password
    
    # --- CORREÇÃO AQUI ---
    # O disco foi movido para o nível de serviço correto.
    disks:
      - name: n8n-data
        mountPath: /home/node/.n8n
        sizeGB: 1 # É uma boa prática definir um tamanho para o disco

  # Serviço para o Banco de Dados PostgreSQL
  - name: postgres
    type: pserv
    image:
      url: postgres:13
    plan: free # Define o plano, 'free' é uma opção comum para testes
    postgresMajorVersion: 13
