# render.yaml
# Estrutura completa para deploy do n8n com um banco de dados PostgreSQL na Render

services:
  # Serviço 1: Aplicação Web do n8n
  - type: web
    name: n8n
    env: node
    # Define o repositório do n8n para a Render clonar e construir
    repo: https://github.com/n8n-io/n8n.git
    branch: master
    # Comandos para instalar dependências e construir a aplicação
    buildCommand: npm install && npm run build
    # Comando para iniciar a aplicação
    startCommand: npm start
    # Porta interna que o n8n usa
    healthCheckPath: /healthz
    # Variáveis de ambiente essenciais para o n8n funcionar
    envVars:
      # Define o tipo de banco de dados
      - key: DB_TYPE
        value: postgresdb
      # Pega o host do banco de dados criado abaixo
      - key: DB_POSTGRESDB_HOST
        fromDatabase:
          name: n8n-db # Deve ser o mesmo nome do serviço do banco de dados
          property: host
      # Pega a porta do banco de dados
      - key: DB_POSTGRESDB_PORT
        fromDatabase:
          name: n8n-db
          property: port
      # Pega o nome de usuário do banco de dados
      - key: DB_POSTGRESDB_USER
        fromDatabase:
          name: n8n-db
          property: user
      # Pega a senha do banco de dados
      - key: DB_POSTGRESDB_PASSWORD
        fromDatabase:
          name: n8n-db
          property: password
      # Pega o nome do banco de dados
      - key: DB_POSTGRESDB_DATABASE
        fromDatabase:
          name: n8n-db
          property: database
      # Define a URL base da aplicação (importante para webhooks)
      - key: WEBHOOK_URL
        fromService:
          type: web
          name: n8n # Deve ser o mesmo nome deste serviço
          property: url
      # Outra variável de URL que pode ser necessária
      - key: N8N_HOST
        fromService:
          type: web
          name: n8n
          property: url
    # Disco persistente para os dados do n8n (workflows, credenciais, etc.)
    disks:
      - name: n8n-data
        mountPath: /home/node/.n8n
        sizeGB: 1

# Seção para definir o banco de dados
databases:
  # Serviço 2: Banco de Dados PostgreSQL
  - name: n8n-db
    # 'plan: free' pode ser usado se disponível no seu plano
    plan: free
    # Define a versão do PostgreSQL
    postgresMajorVersion: 13
